FROM amazoncorretto:23-alpine3.20-full
LABEL authors="pintu"
RUN mkdir /opt/app
WORKDIR /opt/app
ARG JAR_FILE=target/BasicSpringBoot-1.0.0.jar
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_URL
ARG KEYCLOAK_BASE_URL
ARG KEYCLOAK_REALM
ARG KEYCLOAK_CLIENT_ID
ARG KEYCLOAK_CLIENT_SECRET
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_URL=${DB_URL}
ENV KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
ENV KEYCLOAK_REALM=${KEYCLOAK_REALM}
ENV KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
ENV KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
ADD ${JAR_FILE} /opt/app/app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/opt/app/app.jar"]
