server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
spring:
  datasource:
    password: admin@235
    username: root
    url: jdbc:mysql://localhost:3308/sample_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
#  boot:
#    admin:
#      client:
#        url: http://localhost:8081
basic:
  base_url: ${BASE_URL:localhost:8087}
  realm: ${REALM:basic-service}
  client_id: ${CLIENT_ID:basic-client}
  client_secret: ${CLIENT_SECRET:JsMTY7Ur8ug4SEVeOljr2XGsadRt0bG4}
logging:
  level:
    org.springframework: info
    #    org.springframework: debug
    org.springframework.security: debug